spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      label: master
      server:
        native:
          search-locations: classpath:/config
        #git:
        #  uri: https://github.com/MikeChengege/SpringCloud/
        #  searchPaths: respo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/