eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product-service-zuul
zuul:
  routes:
    api-a:
      path: /api-data/**
      serviceId: PRODUCT-DATA-SERVICE
      sensitiveHeaders: "*"
    api-b:
      path: /**
      serviceId: PRODUCT-VIEW-SERVICE-FEIGN
      sensitiveHeaders: "*"
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 500